image: go_build:1.15

variables:
  SRC: "/go/src/fdps"
  CHIEF_RELEASE: "1.0.0"
  CHANNEL_RELEASE: "1.0.0"

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
 
stages:
  - build
  - deploy
  
build:
  stage: build
  only:
    - redis_log
  script: 
  - git clone ssh://git@192.168.1.24:222/fdps/fmtp.git $SRC/fmtp
  - cd  $SRC/fmtp
  - git checkout redis_log
  - git pull  
  - mkdir -p $SRC/mods 
  - git clone ssh://git@192.168.1.24:222/go_utils/logger.git $SRC/mods/logger
  - git clone ssh://git@192.168.1.24:222/go_utils/prom_metrics.git $SRC/mods/prom_metrics
  - git clone ssh://git@192.168.1.24:222/go_utils/web_sock.git $SRC/mods/web_sock  
  - git clone ssh://git@192.168.1.24:222/go_utils/utils.git $SRC/mods/utils  
  - cp -r $SRC/fmtp/docker/* $CI_PROJECT_DIR/$CI_PROJECT_NAME
  - mkdir -p $CI_PROJECT_DIR/$CI_PROJECT_NAME/channel/fdps
  - mkdir -p $CI_PROJECT_DIR/$CI_PROJECT_NAME/chief/fdps/logs
  - cd  $SRC/fmtp/channel
  - go build  -o $CI_PROJECT_DIR/$CI_PROJECT_NAME/channel/fdps/fmtp_channel
  - cd  $SRC/fmtp/chief
  - go build -ldflags "-X fdps/fmtp/chief/version.Release=${CHIEF_RELEASE} -X fdps/fmtp/chief/version.Commit=$(git rev-parse --short HEAD) -X fdps/fmtp/chief/version.BuildTime=`date +%Y-%m-%dT%H:%M:%S`" -o $CI_PROJECT_DIR/$CI_PROJECT_NAME/chief/fdps/fmtp_chief

        
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$CI_PROJECT_NAME/
      
deploy:  
  stage: deploy
  only:
    - redis_log
  script:
  
  - ssh sasha@192.168.1.24 "mkdir -p ~/docker/$CI_PROJECT_NAME"
  - scp -r $CI_PROJECT_DIR/$CI_PROJECT_NAME/* sasha@192.168.1.24:/home/sasha/docker/$CI_PROJECT_NAME
  - ssh sasha@192.168.1.24 "cd ~/docker/$CI_PROJECT_NAME/channel && docker build -t fmtp_channel:${CHANNEL_RELEASE} . --no-cache"
  - ssh sasha@192.168.1.24 "cd ~/docker/$CI_PROJECT_NAME/chief && docker-compose down" 
  - ssh sasha@192.168.1.24 "cd ~/docker/$CI_PROJECT_NAME/chief && docker build -t fmtp_chief:${CHIEF_RELEASE} . --no-cache && docker-compose up -d"  
  - ssh sasha@192.168.1.24 "mkdir -p ~/docker/$CI_PROJECT_NAME/channel/image_tars && cd ~/docker/$CI_PROJECT_NAME/channel/image_tars && docker save -o fmtp_channel-${CHANNEL_RELEASE}.tar fmtp_channel:${CHANNEL_RELEASE}"  
  - ssh sasha@192.168.1.24 "mkdir -p ~/docker/$CI_PROJECT_NAME/chief/image_tars && cd ~/docker/$CI_PROJECT_NAME/chief/image_tars && docker save -o fmtp_chief-${CHIEF_RELEASE}.tar fmtp_chief:${CHIEF_RELEASE}"
  