image: go_build:1.15

variables:
  SRC: "/go/src/fdps"
  CHIEF_RELEASE: "0.0.6"
  CHANNEL_RELEASE: "0.0.3"

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  
stages:
  - build
  - deploy
  
build:
  stage: build
  script: 
  - git clone ssh://git@192.168.1.24:222/fdps/fmtp.git $SRC/fmtp
  - git clone ssh://git@192.168.1.24:222/fdps/utils.git $SRC/utils
  - cd  $SRC/fmtp-scr
  - git checkout develop  
  - git pull 
  - cd  $SRC/utils
  - git checkout develop  
  - git pull
  - cp -r $SRC/fmtp-scr/docker/* $CI_PROJECT_DIR/$CI_PROJECT_NAME
  - mkdir -p $CI_PROJECT_DIR/$CI_PROJECT_NAME/channel/fdps
  - mkdir -p $CI_PROJECT_DIR/$CI_PROJECT_NAME/chief/fdps/logs
  - cd  $SRC/fmtp-scr/channel
  - go build  -o $CI_PROJECT_DIR/$CI_PROJECT_NAME/channel/fdps/fmtp_channel
  - cd  $SRC/fmtp-scr/chief
  - go build -ldflags "-X fdps/fmtp-scr/chief/version.Release=${CHIEF_RELEASE} -X fdps/fmtp-scr/chief/version.Commit=$(git rev-parse --short HEAD) -X fdps/fmtp-scr/chief/version.BuildTime=`date +%Y-%m-%dT%H:%M:%S`" -o $CI_PROJECT_DIR/$CI_PROJECT_NAME/chief/fdps/fmtp_chief
  
        
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$CI_PROJECT_NAME/
      
deploy:
  stage: deploy
  script:
  
  - ssh sasha@192.168.1.24 "mkdir -p ~/docker/$CI_PROJECT_NAME"
  - scp -r $CI_PROJECT_DIR/$CI_PROJECT_NAME/* sasha@192.168.1.24:/home/sasha/docker/$CI_PROJECT_NAME
  - ssh sasha@192.168.1.24 "cd ~/docker/$CI_PROJECT_NAME/channel && docker build -t fmtp_channel:${CHANNEL_RELEASE} . --no-cache"
  - ssh sasha@192.168.1.24 "cd ~/docker/$CI_PROJECT_NAME/chief && docker-compose down"  
  - ssh sasha@192.168.1.24 "cd ~/docker/$CI_PROJECT_NAME/chief && docker build -t fmtp_chief:${CHIEF_RELEASE} . --no-cache && docker-compose up -d"  
  - ssh sasha@192.168.1.24 "mkdir -p ~/docker/$CI_PROJECT_NAME/channel/image_tars && cd ~/docker/$CI_PROJECT_NAME/channel/image_tars && docker save -o fmtp_channel-${CHANNEL_RELEASE}.tar fmtp_channel:${CHANNEL_RELEASE}"  
  - ssh sasha@192.168.1.24 "mkdir -p ~/docker/$CI_PROJECT_NAME/chief/image_tars && cd ~/docker/$CI_PROJECT_NAME/chief/image_tars && docker save -o fmtp_chief-${CHIEF_RELEASE}.tar fmtp_chief:${CHIEF_RELEASE}"
  