// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: fmtp.proto

package fmtp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid    string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`       // ид назначения или ид отправителя
	Tp     string                 `protobuf:"bytes,2,opt,name=tp,proto3" json:"tp,omitempty"`         // тип сообщения (operational)
	Txt    string                 `protobuf:"bytes,3,opt,name=txt,proto3" json:"txt,omitempty"`       // текст сообщения
	Id     string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`         // ид сообщения (произвольная строка)
	Rrtime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=rrtime,proto3" json:"rrtime,omitempty"` // время получения сообщения из канала fmtp
	Rqtime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=rqtime,proto3" json:"rqtime,omitempty"` // время отправки в сервис олди
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmtp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_fmtp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_fmtp_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Msg) GetTp() string {
	if x != nil {
		return x.Tp
	}
	return ""
}

func (x *Msg) GetTxt() string {
	if x != nil {
		return x.Txt
	}
	return ""
}

func (x *Msg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Msg) GetRrtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Rrtime
	}
	return nil
}

func (x *Msg) GetRqtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Rqtime
	}
	return nil
}

type MsgList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Msg `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *MsgList) Reset() {
	*x = MsgList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmtp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgList) ProtoMessage() {}

func (x *MsgList) ProtoReflect() protoreflect.Message {
	mi := &file_fmtp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgList.ProtoReflect.Descriptor instead.
func (*MsgList) Descriptor() ([]byte, []int) {
	return file_fmtp_proto_rawDescGZIP(), []int{1}
}

func (x *MsgList) GetList() []*Msg {
	if x != nil {
		return x.List
	}
	return nil
}

type SvcReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // произвольные данные
}

func (x *SvcReq) Reset() {
	*x = SvcReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmtp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcReq) ProtoMessage() {}

func (x *SvcReq) ProtoReflect() protoreflect.Message {
	mi := &file_fmtp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcReq.ProtoReflect.Descriptor instead.
func (*SvcReq) Descriptor() ([]byte, []int) {
	return file_fmtp_proto_rawDescGZIP(), []int{2}
}

func (x *SvcReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SvcResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errormessage string `protobuf:"bytes,1,opt,name=errormessage,proto3" json:"errormessage,omitempty"` // сообщение об ошибке
}

func (x *SvcResult) Reset() {
	*x = SvcResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmtp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvcResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcResult) ProtoMessage() {}

func (x *SvcResult) ProtoReflect() protoreflect.Message {
	mi := &file_fmtp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcResult.ProtoReflect.Descriptor instead.
func (*SvcResult) Descriptor() ([]byte, []int) {
	return file_fmtp_proto_rawDescGZIP(), []int{3}
}

func (x *SvcResult) GetErrormessage() string {
	if x != nil {
		return x.Errormessage
	}
	return ""
}

var File_fmtp_proto protoreflect.FileDescriptor

var file_fmtp_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x6d, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x46, 0x6d,
	0x74, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x74, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x72, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x06, 0x72, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x71,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x72, 0x71, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2f,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x46, 0x6d, 0x74, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x1c, 0x0a, 0x06, 0x53, 0x76, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a,
	0x09, 0x53, 0x76, 0x63, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x80,
	0x01, 0x0a, 0x0b, 0x46, 0x6d, 0x74, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39,
	0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x46, 0x6d, 0x74, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x46, 0x6d, 0x74, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x76,
	0x63, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x07, 0x52, 0x65, 0x63,
	0x76, 0x4d, 0x73, 0x71, 0x12, 0x13, 0x2e, 0x46, 0x6d, 0x74, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x76, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x46, 0x6d, 0x74, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6d, 0x74, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fmtp_proto_rawDescOnce sync.Once
	file_fmtp_proto_rawDescData = file_fmtp_proto_rawDesc
)

func file_fmtp_proto_rawDescGZIP() []byte {
	file_fmtp_proto_rawDescOnce.Do(func() {
		file_fmtp_proto_rawDescData = protoimpl.X.CompressGZIP(file_fmtp_proto_rawDescData)
	})
	return file_fmtp_proto_rawDescData
}

var file_fmtp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fmtp_proto_goTypes = []interface{}{
	(*Msg)(nil),                   // 0: FmtpService.Msg
	(*MsgList)(nil),               // 1: FmtpService.MsgList
	(*SvcReq)(nil),                // 2: FmtpService.SvcReq
	(*SvcResult)(nil),             // 3: FmtpService.SvcResult
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_fmtp_proto_depIdxs = []int32{
	4, // 0: FmtpService.Msg.rrtime:type_name -> google.protobuf.Timestamp
	4, // 1: FmtpService.Msg.rqtime:type_name -> google.protobuf.Timestamp
	0, // 2: FmtpService.MsgList.list:type_name -> FmtpService.Msg
	1, // 3: FmtpService.FmtpService.SendMsg:input_type -> FmtpService.MsgList
	2, // 4: FmtpService.FmtpService.RecvMsq:input_type -> FmtpService.SvcReq
	3, // 5: FmtpService.FmtpService.SendMsg:output_type -> FmtpService.SvcResult
	1, // 6: FmtpService.FmtpService.RecvMsq:output_type -> FmtpService.MsgList
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fmtp_proto_init() }
func file_fmtp_proto_init() {
	if File_fmtp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fmtp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fmtp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fmtp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvcReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fmtp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvcResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fmtp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fmtp_proto_goTypes,
		DependencyIndexes: file_fmtp_proto_depIdxs,
		MessageInfos:      file_fmtp_proto_msgTypes,
	}.Build()
	File_fmtp_proto = out.File
	file_fmtp_proto_rawDesc = nil
	file_fmtp_proto_goTypes = nil
	file_fmtp_proto_depIdxs = nil
}
