DROP TABLE PARKINGS;
DROP SEQUENCE PARKINGS_ID_SEQ;
DROP TRIGGER PARKINGS_ID_TRG;
/
COMMIT;
/

CREATE TABLE PARKINGS(
    ID                      INTEGER NOT NULL,
    AIRPORT_ICAO_CODE       NVARCHAR2(4),
    PARKING_NAME            NVARCHAR2(20),
    UNITED_PARKING_NAME     NVARCHAR2(20),
    X_POS                   NUMBER,
    Y_POS                   NUMBER,
    X_POS_AMMEND            NUMBER,
    Y_POS_AMMEND            NUMBER,
    ARCFT_TYPES             NVARCHAR2(200),
    CUR_STATE               NVARCHAR2(20),
    FLIGHT_NUM              NVARCHAR2(20),
    SIDE_NUM                NVARCHAR2(100),
    INFO                    NVARCHAR2(300),
    SECTOR_CODE             NVARCHAR2(2)    
);

COMMENT ON COLUMN PARKINGS.AIRPORT_ICAO_CODE IS 'ICAO код аэродрома';

COMMENT ON COLUMN PARKINGS.PARKING_NAME IS 'Название стоянки';

COMMENT ON COLUMN PARKINGS.UNITED_PARKING_NAME IS 'Название объединенной стоянки';

COMMENT ON COLUMN PARKINGS.X_POS IS 'Координата X на картинке, pixel';

COMMENT ON COLUMN PARKINGS.Y_POS IS 'Координата Y на картинке, pixel';
    
COMMENT ON COLUMN PARKINGS.X_POS_AMMEND IS 'Правка координаты X на картинке, pixel';

COMMENT ON COLUMN PARKINGS.Y_POS_AMMEND IS 'Правка координаты Y на картинке, pixel';

COMMENT ON COLUMN PARKINGS.ARCFT_TYPES IS  'Типы принимаемых ВС';

COMMENT ON COLUMN PARKINGS.CUR_STATE IS 'Соятояние';

COMMENT ON COLUMN PARKINGS.FLIGHT_NUM IS 'Номер рейса';

COMMENT ON COLUMN PARKINGS.SIDE_NUM IS 'Бортовой номер';

COMMENT ON COLUMN PARKINGS.INFO IS 'Примечания';

COMMENT ON COLUMN PARKINGS.SECTOR_CODE IS 'Код сектора, изменившего состояние';

ALTER TABLE PARKINGS ADD CONSTRAINT PARKINGS_PK PRIMARY KEY(ID);

CREATE SEQUENCE PARKINGS_ID_SEQ START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER PARKINGS_ID_TRG BEFORE
    INSERT ON PARKINGS
    FOR EACH ROW
    WHEN(NEW.ID IS NULL)
BEGIN
    :NEW.ID := PARKINGS_ID_SEQ.NEXTVAL;
END;
/
COMMIT;
/

