-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1059
--   at:        2018-06-06 18:10:53 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


CREATE TABLE CONTROLLERS (
    CONTROLLERID            NUMBER NOT NULL,
    IP                      NVARCHAR2(15),
    DAEMONSPORT             NUMBER,
    OLDIPROVIDERPORT        NUMBER,
    OLDIPROVIDERENCODING    NVARCHAR2(20),
    AODBPROVIDERPORT        NUMBER,
    VERSIONS                NVARCHAR2(1000)
);

ALTER TABLE CONTROLLERS ADD CONSTRAINT CONTROLLER_PK PRIMARY KEY ( CONTROLLERID );

/
COMMIT;
/

CREATE TABLE DAEMONS (
    DAEMONID                NUMBER NOT NULL,
    VERSION                 NVARCHAR2(20),
    DATATYPE                NVARCHAR2(10),
    NETROLE                 NVARCHAR2(10),
    LOCALNAME               NVARCHAR2(32),
    LOCALATC                NVARCHAR2(32),
    REMOTENAME              NVARCHAR2(32),
    REMOTEATC               NVARCHAR2(32),
    TS                      NUMBER,
    TR                      NUMBER,
    TI                      NUMBER,
    RECONNECTTIMEOUT        NUMBER,
    FMTPINITSTATE           NVARCHAR2(15),
    REMOTEADDRESS1          NVARCHAR2(15),
    REMOTEPORT1             NUMBER,
    REMOTEADDRESS2          NVARCHAR2(15),
    REMOTEPORT2             NUMBER,
    REMOTEADDRESS           NVARCHAR2(15),
    REMOTEPORT              NUMBER,
    LOCALPORT               NUMBER,
    DEBUGLOG                NVARCHAR2(3),
    STATE                   NVARCHAR2(7),
    DATAENCODING            NVARCHAR2(20)
);

ALTER TABLE DAEMONS ADD CONSTRAINT DAEMON_PK PRIMARY KEY ( DAEMONID );

/
COMMIT;
/

CREATE TABLE LOGGER (
    LOGGERID                NUMBER DEFAULT 1 NOT NULL ENABLE, 
	LOGGERPORT              NUMBER, 
	BOOSTFILESIZEKB         NUMBER, 
	BOOSTFOLDERSIZEGB       NUMBER, 
	ROACHHOSTNAME           NVARCHAR2(100), 
	ROACHDATABASE           NVARCHAR2(100), 
	ROACHPORT               NUMBER, 
	ROACHUSER               NVARCHAR2(100), 
	ROACHPASSWORD           NVARCHAR2(100), 
	ROACHMAXLOGSTORECOUNT   NUMBER, 
	ROACHSTOREDAYS          NUMBER
)
  
/
COMMIT;
/

CREATE TABLE PROVIDERS (
    PROVIDERID       NUMBER NOT NULL,
    PROVIDERIP       NVARCHAR2(255),
    PROVIDERSTATUS   NVARCHAR2(10),
    PROVIDERTYPE     NVARCHAR2(10)
);

ALTER TABLE PROVIDERS ADD CONSTRAINT PROVIDERS_PK PRIMARY KEY ( PROVIDERID );

/
COMMIT;
/

CREATE SEQUENCE CONTROLLERS_CONTROLLERID_SEQ START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER CONTROLLERS_CONTROLLERID_TRG BEFORE
    INSERT ON CONTROLLERS
    FOR EACH ROW
BEGIN
    :NEW.CONTROLLERID := CONTROLLERS_CONTROLLERID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE DAEMONS_DAEMONID_SEQ START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER DAEMONS_DAEMONID_TRG BEFORE
    INSERT ON DAEMONS
    FOR EACH ROW
BEGIN
    :NEW.DAEMONID := DAEMONS_DAEMONID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE PROVIDERS_PROVIDERID_SEQ START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER PROVIDERS_PROVIDERID_TRG BEFORE
    INSERT ON PROVIDERS
    FOR EACH ROW
BEGIN
    :NEW.PROVIDERID := PROVIDERS_PROVIDERID_SEQ.NEXTVAL;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              3
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
